### ISSUE TITLE
Does CondaPkg suppot to install local whl file and the package from Git?

### ISSUE THREAD

**Issue by WJ-Huang** [cjdoris/CondaPkg.jl#17]
Hi, thank you for the nice package. It helps me a lot! But when I used the package, I faced two difficulties. 
Firstly, when I want to install a local `.whl` file in Python, I can do the following commands in the terminal
```
cd C:/path/to/the/file
pip install name_of_the_file.whl
```
Secondly, if I want to install some package from Github, I can run the command
```
pip install https://github.com/.../master.zip
```
Does CondaPkg support these two ways to install a package? Thank you!

**Comment by cjdoris** [comment]
Not right now, but it would be hard to add. I'll put it on my to-do list.

**Comment by cjdoris** [comment]
Actually something like the following should currently work:
```julia
CondaPkg.add("name", version="@ url_or_path")
```

**Comment by WJ-Huang** [comment]
Thanks!
