### ISSUE TITLE
To do: don't always create a new conda env

### ISSUE THREAD

**Issue by cjdoris** [cjdoris/CondaPkg.jl#2]
If an env already exists, just figure out what needs to be added and removed.

**Comment by thautwarm** [comment]
Also in need of this. Now with `JULIA_CONDAPKG_EXE` it's easy to use an existing conda executable, but it seems that we could not use an existing conda environment other than that in `$PYTHON_JULIAPKG_PROJECT/.CondaPkg`.

I'd suggest adding an environment variable `JULIA_CONDAPKG_ENV`. The default behaviour is the current one, and if `JULIA_CONDAPKG_ENV` is specified, the existing conda environment is activated and used.

**Comment by cjdoris** [comment]
Closing as this was done a while ago.

@thautwarm You can already do this by having the conda environment you want to use already activated before you start Julia, and set `JULIA_CONDAPKG_BACKEND=Null`. If that's not sufficient feel free to open a new ticket.
