### ISSUE TITLE
pip command-line options like --no-binary

### ISSUE THREAD

**Issue by xzackli** [cjdoris/CondaPkg.jl#26]
Can the pip packagespec be expanded to include flags like `--no-binary ...`? There is a package called [ducc](https://pypi.org/project/ducc0/) for SHT/FFT that benefits significantly from the flag, due to specializing on CPU instructions of the target machine.

```
pip3 install --no-binary ducc0 ducc0
```

**Comment by cjdoris** [comment]
I'm having a think. Are there other flags of interest?

**Comment by xzackli** [comment]
Not for me personally! I think most of the pip flags are not relevant for CondaPkg. 

I do have a distant memory of having to use `--no-deps` for some python package one time (maybe for [sage](https://trac.sagemath.org/ticket/32492)?)

**Comment by cjdoris** [comment]
This is implemented now, and will appear in a release today.

From the REPL, you can do `pkg> conda pip_add --binary=no ducc0` for your example (there is also `--binary=only`).

**Comment by xzackli** [comment]
Amazing, thank you!
