### ISSUE TITLE
To do: Support pip dependencies

### ISSUE THREAD

**Issue by cjdoris** [cjdoris/CondaPkg.jl#3]

**Comment by diegozea** [comment]
Thanks for this project! I am using Conda to install a mix of PyPI and Conda packages in a private Julia package, so I would love this feature to migrate towards CondaPkg that looks a lot cleaner :) Best,

**Comment by cjdoris** [comment]
Yeah it's a brand new project, but pip support is near the top of my priorities. Feel free to watch this issue for updates.

**Comment by cjdoris** [comment]
Done, but see #13.

**Comment by diegozea** [comment]
Thanks! :)
