### ISSUE TITLE
Concurrent resolve with multiple processes

### ISSUE THREAD

**Issue by amilsted** [cjdoris/CondaPkg.jl#40]
I'm seeing an issue when trying to `use` a package `X` that in turn uses CondaPkg to manage PythonCall dependencies. The problem occurs when trying to launch many simultaneous jobs, each `using X`, on a cluster.

For whatever reason, each job does a full resolve and tries to read and write the meta file. The file is not protected by any locks, so we sometimes get a stacktrace like this:
```
  [1] EOFError: read end of file
Stacktrace:
  [1] readread((readread(read((read(s::s::ss::s::::IOStreamIOStream, T::IOStream, T::IOStream, T::IOStream, T::, T::s::Type{Int64})
    @ Type{Int64})
    @ Type{Int64})
    @ TypeType{Int64})
    @ {Int64})
    @ IOStream, T::Type{Int64})
    @ BaseBase Base  Base Base ./././././Base ./iostream.jl:412iostream.jl:412
  [2] read_meta(iostream.jl:412
  [2]io::IO)
    @ CondaPkg  read_meta(io::~/.julia/packages/CondaPkg/OrrdF/src/meta.jl:21
  [3] IO)
    @ CondaPkg ~/.julia/packages/CondaPkg/OrrdF/src/meta.jl:21
  [3] 
iostream.jl:412 
  [2] read_meta(io::IO)
    @ CondaPkg ~/.julia/packages/CondaPkg/OrrdF/src/meta.jl:21
  [3]  [2] read_meta(io::IO)
    @ CondaPkg ~/.julia/packages/CondaPkg/OrrdF/src/meta.jl:21
  [3] iostream.jl:412
  [2] read_meta(io::IO)
    @ CondaPkg ~/.julia/packages/CondaPkg/OrrdF/src/meta.jl:21
  [3] open(f::typeof(CondaPkg.read_meta), args::open(f::typeof(CondaPkg.read_meta), args::String; kwargs::String; kwargs::open(f::typeof(CondaPkg.read_meta), args::String; kwargs::open(f::typeof(CondaPkg.read_meta), args::String; kwargs::iostream.jl:412
  [2] read_meta(io::IO)
    @ CondaPkg ~/.julia/packages/CondaPkg/OrrdF/src/meta.jl:21open(f::
  [3] typeof(CondaPkg.read_meta), args::String; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./io.jl:330
Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./io.jl:330
  [4] Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./io.jl:330
  [4] Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./io.jl:330
  [4] open(f::Function, args::String  [4] open(f::Function, args::String)
    @ Base ./open(f::Function, args::String)
    @ Base ./io.jl:328
open(f::Function, args::String)
    @ Base ./io.jl:328
  [5] )
    @ Base ./io.jl:328
  [5] io.jl:328
  [5]   [5] resolve(; force::resolve(; force::Bool, ioresolve(; force::Bool, ioresolve(; force::BoolBool, io::IO, interactive::Bool, dry_run::Bool::IO, interactive::Bool, dry_run::Bool)::IO, interactive::Bool, dry_run::Bool)
, io::IO, interactive::Bool, dry_run::Bool    @ CondaPkg ~/.julia/packages/CondaPkg/OrrdF/src/resolve.jl:349
)
    @ CondaPkg ~/.julia/packages/CondaPkg/OrrdF/src/resolve.jl:349
 
    @ CondaPkg ~/.julia/packages/CondaPkg/OrrdF/src/resolve.jl:349
  [6])
    @ CondaPkg ~/.julia/packages/CondaPkg/OrrdF/src/resolve.jl:349
 resolve()
    @ CondaPkg   [6] resolve()
    @ CondaPkg ~/.julia/packages/CondaPkg/OrrdF/src/ [6] resolve()
    @ CondaPkg ~/.julia/packages/CondaPkg/OrrdF/src/resolve.jl:303  [6] resolve()
    @ CondaPkg ~/.julia/packages/CondaPkg/OrrdF/src/resolve.jl:303
  [7]
  [7] envdir()
    @ ~/.julia/packages/CondaPkg/OrrdF/src/resolve.jl:303
  [7] envdir()
    @ CondaPkgresolve.jl:303
  [7] envdir()
    @ CondaPkg  ~/.julia/packages/CondaPkg/OrrdF/src/env.jl:70
~/.julia/packages/CondaPkg/OrrdF/src/env.jl:70
 envdir()
    @ CondaPkg ~/.julia/packages/CondaPkg/OrrdF/src/env.jl:70
CondaPkg ~/.julia/packages/CondaPkg/OrrdF/src/env.jl:70
  [8]   [8] init_context  [8]   [8] init_context()
    @ PythonCall.C init_context()
    @ PythonCall.C ()
    @ PythonCall.C init_context()
```

This is with a single pip dependency in the `CondaPkg.toml`. I get a bunch of log messages that are apparently coming from[ this line ](https://github.com/cjdoris/CondaPkg.jl/blob/d1aaa7056626ad24fc62e7a9190763b96cda947d/src/resolve.jl#L399) and [this line](https://github.com/cjdoris/CondaPkg.jl/blob/d1aaa7056626ad24fc62e7a9190763b96cda947d/src/resolve.jl#L58).

As a workaround, it would be nice to be able to force CondaPkg not to resolve, say via an environment variable. In my problem example, the dependencies are always found to be up to date in any case.

**Comment by cjdoris** [comment]
Ah yeah, fair enough, I should use file locks when resolving so only one process resolves at a time (then the others should automatically skip resolving). Should be simple to add I think.

> As a workaround, it would be nice to be able to force CondaPkg not to resolve, say via an environment variable. In my problem example, the dependencies are always found to be up to date in any case.

You can set `JULIA_CONDAPKG_BACKEND=Null` (https://github.com/cjdoris/CondaPkg.jl#backends).

**Comment by amilsted** [comment]
Tried that, but PythonCall didn't like it (didn't get a valid python path for some reason). What worked was setting `JULIA_PYTHONCALL_EXE` as per [these instructions](https://cjdoris.github.io/PythonCall.jl/stable/pythoncall/#If-you-don't-want-to-use-Conda).

**Comment by cjdoris** [comment]
Oh, you're right, that's not what you want. The Null backend assumes you are already running in a pre-existing Conda environment. What you need is an "offline mode" to use the environment managed by CondaPkg, but just skip resolving anything. I've been meaning to add that (I already have it over in pyjuliapkg).

Setting `JULIA_PYTHONCALL_EXE` to the Python executable in a non-activated Conda environment is not always reliable. Because it skips the initialisation of the environment, some packages will not work properly, but it really depends on what packages you're using, most are fine.

**Comment by amilsted** [comment]
It should work okay if I manually activate the conda env I want before I start julia, no? With `JULIA_PYTHONCALL_EXE` set to the python path for that conda env?

**Comment by cjdoris** [comment]
Yeah sure, if you activate the environment yourself all is fine.

**Comment by cjdoris** [comment]
I have added locking around the main resolve routine, so only one process should resolve at a time now - the others will wait until the first has finished, and then should immediately finish themselves because everything is already up-to-date.

Can you please try this out by installing CondaPkg from the main branch (`pkg> add CondaPkg#main`) and let me know if it works for you?

**Comment by amilsted** [comment]
Will test this out soon.

**Comment by amilsted** [comment]
Seems to be working now. Will reopen if we see any further issues!
