### ISSUE TITLE
`pip_add` REPL typo?

### ISSUE THREAD

**Issue by icweaver** [cjdoris/CondaPkg.jl#51]
Just noticed this super tiny issue:

```julia
(pythoncall_main) pkg> conda pip

pip add     pip_remove
```

The tab complete hint for `pip_add` seems to suggests `pip add` instead. Should this line use `pip_add` instead?

https://github.com/cjdoris/CondaPkg.jl/blob/75ef6edef098cc37a13427e8291f54c7beca05c2/src/PkgREPL.jl#L183

**Comment by cjdoris** [comment]
Thanks, just fixed it on main :)
