### ISSUE TITLE
CondaPkg dependencies uninstalled when loading locally from global Julia environment

### ISSUE THREAD

**Issue by stillyslalom** [cjdoris/CondaPkg.jl#66]
I have a package, [PyThermo](https://github.com/stillyslalom/PyThermo.jl), which uses CondaPkg to manage its Python dependencies. I use it often, so PyThermo is installed in my global `v1.9` environment. If I load it from a local project environment without first `Pkg.add`ing it, its Conda dependencies are not specified in the local project environment, so CondaPkg removes them (from the *global environment*), breaking the package in both the local and the global environments.
```
(@v1.9) pkg> st
Status `C:\Users\aames\.julia\environments\v1.9\Project.toml`
  [6fae04a5] PyThermo v0.2.2

(@v1.9) pkg> activate --temp
  Activating new project at `C:\Users\aames\AppData\Local\Temp\jl_Mv4OQW`

julia> using PyThermo
    CondaPkg Resolving changes
             - python
             - thermo
    CondaPkg Removing packages
             │ C:\Users\aames\.julia\artifacts\4b82d7ce236527959584cbf6b4cd3a10545b99ac\bin\micromamba.exe
             │ -r C:\Users\aames\.julia\scratchspaces\0b3b1443-0f03-428d-bdfb-f27f9c1191ea\root
             │ remove
             │ -y
             │ -p C:\Users\aames\.julia\environments\v1.9\.CondaPkg\env
             │ python
             └ thermo
[...]
Unlinking tk-8.6.12-h8ffe710_0
Unlinking openssl-3.0.7-hcfcfb64_1
Unlinking libsqlite-3.40.0-hcfcfb64_0
Unlinking libffi-3.4.2-h8ffe710_5
Unlinking bzip2-1.0.8-h8ffe710_4
Unlinking ca-certificates-2022.12.7-h5b45459_0
Transaction finished

ERROR: InitError: Python executable "C:\\Users\\aames\\.julia\\environments\\v1.9\\.CondaPkg\\env\\python.exe" is not executable.
Stacktrace:
  [1] error
    @ .\error.jl:35
  [2] init_context()
    @ PythonCall.C C:\Users\aames\.julia\packages\PythonCall\3GRYN\src\cpython\context.jl:88

(jl_Mv4OQW) pkg> add PyThermo
    Updating registry at `C:\Users\aames\.julia\registries\General.toml`
   Resolving package versions...
    Updating `C:\Users\aames\AppData\Local\Temp\jl_WAMdIz\Project.toml`
  [6fae04a5] + PyThermo v0.2.2
    Updating `C:\Users\aames\AppData\Local\Temp\jl_WAMdIz\Manifest.toml`
  [992eb4ea] + CondaPkg v0.2.16
  [187b0558] + ConstructionBase v1.4.1

julia> using PyThermo
ERROR: InitError: UndefRefError: access to undefined reference
Stacktrace:
  [1] PyUnicode_DecodeUTF8
    @ C:\Users\aames\.julia\packages\PythonCall\3GRYN\src\cpython\pointers.jl:299 [inlined]
```

Ideally CondaPkg would follow Pkg's lead in looking for dependencies in global shared environments and using them instead of removing them.

**Comment by cjdoris** [comment]
Thanks - this is indeed a bug. All dependencies of anything in the load path are intended to be installed, but I can see why it isn't. Should be easy to fix.

@t-bltg nope not a regression, this has been there forever!

**Comment by cjdoris** [comment]
OK I think I've fixed it in the `loadpath` branch.  Please can you try it as follows and let me know if it works.
```
pkg> activate --temp
pkg> add CondaPkg#loadpath
julia> using PyThermo
```

**Comment by stillyslalom** [comment]
Works! Thanks for the quick fix. Would it be possible to default to loading from a global `v1.9-conda` environment (from https://github.com/cjdoris/CondaPkg.jl/issues/64) if the dependency is specified in that environment, instead of creating a new environment? Loading and linking Conda packages (from cache) into the new environment takes about 30 seconds on a fast machine, which adds some TTFP pain.

**Comment by cjdoris** [comment]
CondaPkg puts its Conda environment into the topmost project of your load path which depends on CondaPkg. This means that if v1.9 has depends on CondaPkg but your stacked project does not (which is the case in the above example) then the v1.9 environment is reused and no further resolving should occur.

If this isn't the behaviour you observe, please open a new issue.
