### ISSUE TITLE
CondaPkg got stuck on Windows

### ISSUE THREAD

**Issue by BoundaryValueProblems** [cjdoris/CondaPkg.jl#81]
I reported the problem of PythonCall.jl on my Windows machine: https://github.com/cjdoris/PythonCall.jl/issues/284 A similar thing happens for CondaPkg.jl. The test always passes without any problems. Also I can run `using CondaPkg` on the plain REPL or vscode. But then when I try to run any of CondaPkg functions, such as `CondaPkg.status()`, it hangs and the julia prompt never returns. What's wrong here? The version of CondaPkg.jl is v0.2.17, which is the latest one. Julia version is v 1.8.5.
Thanks for your help!

**Comment by cjdoris** [comment]
Can you run `CondaPkg.status(interactive=true)` please? My guess is that there's a lock file lying around. If so, its path will be printed to the screen and you can safely delete it.
